# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("Dialog")
        self.resize(400, 240)
        self.variety_label = QtWidgets.QLabel(self)
        self.variety_label.setGeometry(QtCore.QRect(5, 5, 100, 20))
        self.variety_label.setObjectName("variety_label")
        self.roasting_label = QtWidgets.QLabel(self)
        self.roasting_label.setGeometry(QtCore.QRect(5, 40, 100, 20))
        self.roasting_label.setObjectName("roasting_label")
        self.ground_or_grains_label = QtWidgets.QLabel(self)
        self.ground_or_grains_label.setGeometry(QtCore.QRect(5, 75, 101, 20))
        self.ground_or_grains_label.setObjectName("ground_or_grains_label")
        self.taste_description_label = QtWidgets.QLabel(self)
        self.taste_description_label.setGeometry(QtCore.QRect(5, 110, 101, 20))
        self.taste_description_label.setObjectName("taste_description_label")
        self.price_label = QtWidgets.QLabel(self)
        self.price_label.setGeometry(QtCore.QRect(5, 145, 100, 20))
        self.price_label.setObjectName("price_label")
        self.packing_volume_label = QtWidgets.QLabel(self)
        self.packing_volume_label.setGeometry(QtCore.QRect(5, 180, 100, 20))
        self.packing_volume_label.setObjectName("packing_volume_label")
        self.price_spinbox = QtWidgets.QSpinBox(self)
        self.price_spinbox.setGeometry(QtCore.QRect(120, 145, 271, 20))
        self.price_spinbox.setMaximum(1000000000)
        self.price_spinbox.setObjectName("price_spinbox")
        self.packing_volume_spinbox = QtWidgets.QSpinBox(self)
        self.packing_volume_spinbox.setGeometry(QtCore.QRect(120, 180, 271, 20))
        self.packing_volume_spinbox.setMaximum(100000)
        self.packing_volume_spinbox.setObjectName("packing_volume_spinbox")
        self.taste_description_line_edit = QtWidgets.QLineEdit(self)
        self.taste_description_line_edit.setGeometry(QtCore.QRect(120, 110, 271, 20))
        self.taste_description_line_edit.setObjectName("taste_description_line_edit")
        self.variety_line_edit = QtWidgets.QLineEdit(self)
        self.variety_line_edit.setGeometry(QtCore.QRect(120, 5, 271, 20))
        self.variety_line_edit.setObjectName("variety_line_edit")
        self.confirm_btn = QtWidgets.QPushButton(self)
        self.confirm_btn.setGeometry(QtCore.QRect(10, 210, 381, 23))
        self.confirm_btn.setObjectName("confirm_btn")
        self.ground_or_grains_combo_box = QtWidgets.QComboBox(self)
        self.ground_or_grains_combo_box.setGeometry(QtCore.QRect(120, 75, 271, 20))
        self.ground_or_grains_combo_box.setObjectName("ground_or_grains_combo_box")
        self.ground_or_grains_combo_box.addItem("")
        self.ground_or_grains_combo_box.addItem("")
        self.roasting_combo_box = QtWidgets.QComboBox(self)
        self.roasting_combo_box.setGeometry(QtCore.QRect(120, 40, 271, 20))
        self.roasting_combo_box.setObjectName("roasting_combo_box")
        self.roasting_combo_box.addItem("")
        self.roasting_combo_box.addItem("")
        self.roasting_combo_box.addItem("")
        self.roasting_combo_box.addItem("")
        self.roasting_combo_box.addItem("")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Dialog", "Добавление или изменение столбца"))
        self.variety_label.setText(_translate("Dialog", "Название сорта"))
        self.roasting_label.setText(_translate("Dialog", "Степень обжарки"))
        self.ground_or_grains_label.setText(_translate("Dialog", "Молотый/В зернах"))
        self.taste_description_label.setText(_translate("Dialog", "Описание вкуса"))
        self.price_label.setText(_translate("Dialog", "Цена"))
        self.packing_volume_label.setText(_translate("Dialog", "Объем упаковки"))
        self.confirm_btn.setText(_translate("Dialog", "Подтвердить"))
        self.ground_or_grains_combo_box.setItemText(0, _translate("Dialog", "Молотый"))
        self.ground_or_grains_combo_box.setItemText(1, _translate("Dialog", "В зернах"))
        self.roasting_combo_box.setItemText(0, _translate("Dialog", "Светлая"))
        self.roasting_combo_box.setItemText(1, _translate("Dialog", "Средняя"))
        self.roasting_combo_box.setItemText(2, _translate("Dialog", "Темнее средней"))
        self.roasting_combo_box.setItemText(3, _translate("Dialog", "Темная"))
        self.roasting_combo_box.setItemText(4, _translate("Dialog", "Очень темная"))
